tools:
    php_analyzer: true

filter:
    excluded_paths:
        - 'vendor/*'

# Dile a Scrutinizer que use el PHP pre-instalado en lugar de compilar
build:
    environment:
        php:
            version: '8.2' # Al poner '8.2' en lugar de '8.2.0', a veces usa la pre-compilada del contenedor