tools:
    php_analyzer: true

filter:
    excluded_paths:
        - 'vendor/*'    
    dependency_paths:
        - 'phpunit.phar'

# Say to Scrutinizer to use pre-installed PHP instead of compiling one
build:
    dependencies:
        before:
            # Download PHPUnit to analize tests
            - wget https://phar.phpunit.de/phpunit-9.phar -O phpunit.phar
    environment:
        php:
            version: '8.2'             
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            # Scrutinizer tests using kiss autoloader
            - command: 'php phpunit.phar --bootstrap src/autoload.php'
